# Template YAML to submit a training job to AIP. The entire schema for this YAML file is the
# TrainingInput JSON representation, it can be found here:
# https://cloud.google.com/ai-platform/training/docs/reference/rest/v1/projects.jobs#TrainingInput.
#
# If you are just testing, you can use scaleTier: BASIC_GPU. If you have heavier training
# requirements, then you can use the CUSTOM scale tier and set up your masterType and
# masterConfig.acceleratorConfig using the compatibility table found in
# https://cloud.google.com/ai-platform/training/docs/using-gpus.
#
# NOTE that different CPU/GPU combinations have different costs, so bear that in mind when selecting
# your worker types.

# Options available in https://cloud.google.com/ai-platform/training/docs/machine-types#python 
scaleTier: CUSTOM
# masterType only required if using CUSTOM tier
masterType: n1-standard-4
masterConfig:
    # Specify the location of the image. Note that the service account you are using must have
    # permissions to access that location or the location should be public
    imageUri: gcr.io/nplan-scheduling/carlos-aip-test-gpu:hypertune
    # Specify your accelerator here if using CUSTOM tier and you require one
    # Suported accelerators in https://cloud.google.com/ai-platform/training/docs/reference/rest/v1/AcceleratorType
    acceleratorConfig: 
        type: NVIDIA_TESLA_K80
        count: 1
region: us-central1
# If you need access to other google services (e.g. secrets, GCS) you MUST specify a service
# account here.
serviceAccount: pipeline@nplan-scheduling.iam.gserviceaccount.com
# All the input arguments to the docker container go here. If you are hypertuning, you must put here
# the arguments that will be fixed.
args: [
    "--epochs",
    "20",
    "--hypertune", # Only add this argument if you are hypertuning, it will enable the reporting
]
# This bit is only needed if you want to use hypertune, you can see the JSON representation for this
# in the TrainingInputs schema provided above
hyperparameters:
    goal: MINIMIZE
    hyperparameterMetricTag: test_loss
    maxTrials: 6
    maxParallelTrials: 2
    enableTrialEarlyStopping: True
    params:
        - parameterName: hidden-layers
          type: INTEGER
          minValue: 1
          maxValue: 50
        - parameterName: hidden-units
          type: INTEGER
          minValue: 20
          maxValue: 100
        - parameterName: reg-coeff
          type: DOUBLE
          minValue: 0.0000001
          maxValue: 0.1
          scaleType: UNIT_LOG_SCALE
