# Template YAML to submit a training job to AIP. If you are just testing, you can use 
# scaleTier: BASIC_GPU. If you have heavier training requirements, then you can use the CUSTOM scale
# tier and set up your masterType and masterConfig.acceleratorConfig using the compatibility
# table found in https://cloud.google.com/ai-platform/training/docs/using-gpus.
# NOTE that different CPU/GPU combinations have different costs, so bear that in mind when selecting
# your worker types.
scaleTier: CUSTOM # Options available in https://cloud.google.com/ai-platform/training/docs/machine-types#python 
masterType: n1-standard-4 # Only required if using CUSTOM tier
masterConfig:
    imageUri: gcr.io/nplan-scheduling/carlos-aip-test-gpu:wandb
    acceleratorConfig: # Specify your accelerator here if using CUSTOM tier
        # Suported accelerators in https://cloud.google.com/ai-platform/training/docs/reference/rest/v1/AcceleratorType
        type: NVIDIA_TESLA_P100
        count: 1
region: us-central1
# If you need access to other google services (e.g. secrets, GCS) you need to specify a service
# account here.
serviceAccount: pipeline@nplan-scheduling.iam.gserviceaccount.com
# All the input arguments to the docker container go here
args: [
    "--epochs",
    "5",
    "--hidden-layers",
    "15",
    "--use-wandb-secret"
]
