# Dockerfile for a container that does simple training in AIP
FROM python:3.8-slim-bullseye

WORKDIR /root
USER root

# Installs google cloud sdk, this is mostly for using gsutil to export model.
RUN apt-get update && \
    apt-get install -y --no-install-recommends wget && \
    wget -nv https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz && \
    mkdir /root/tools && \
    tar xvzf google-cloud-sdk.tar.gz -C /root/tools && \
    rm google-cloud-sdk.tar.gz && \
    /root/tools/google-cloud-sdk/install.sh --usage-reporting=false \
        --path-update=false --bash-completion=false \
        --disable-installation-options && \
    rm -rf /root/.config/* && \
    ln -s /root/.config /config && \
    # Remove the backup directory that gcloud creates
    rm -rf /root/tools/google-cloud-sdk/.install/.backup

# Path configuration
ENV PATH $PATH:/root/tools/google-cloud-sdk/bin
# Make sure gsutil will use the default service account
RUN echo '[GoogleCompute]\nservice_account = default' > /etc/boto.cfg


# Install the required trainer packages
COPY . aip-trainer

WORKDIR aip-trainer

RUN pip install --upgrade pip && \
    pip install -e . 


ENTRYPOINT ["python", "aip_trainer/trainer.py"]
